source "https://github.com/CocoaPods/Specs.git"
# source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'Demo' do
    use_frameworks!
    pod 'FPSLabel', :path => '../../'
end

